### ISSUE TITLE
有没有maa核心组件手动下载地址，自动一种0％

### ISSUE THREAD

**Issue by KiligLin** [MaaAssistantArknights/MaaX#100]
开了魔法，但是还是一直0％

**Comment by KiligLin** [comment]
关了魔法能下载了……怎么感觉这样不太合理吧

**Comment by ChingCdesu** [comment]
> 关了魔法能下载了……怎么感觉这样不太合理吧

国内网络环境的原因，运营商会有dns劫持，这个完全看运气了

**Comment by AnnAngela** [comment]
> > 关了魔法能下载了……怎么感觉这样不太合理吧
> 
> 国内网络环境的原因，运营商会有dns劫持，这个完全看运气了

其实更有可能是魔法的IP撞速率墙了，maa走的无身份验证api，[单IP限速60次/小时](https://docs.github.com/zh/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits:~:text=%E5%AF%B9%E4%BA%8E%E6%9C%AA%E7%BB%8F%E9%AA%8C%E8%AF%81%E7%9A%84%E8%AF%B7%E6%B1%82%EF%BC%8C%E9%80%9F%E7%8E%87%E9%99%90%E5%88%B6%E5%85%81%E8%AE%B8%E6%AF%8F%E5%B0%8F%E6%97%B6%E6%9C%80%E5%A4%9A%2060%20%E4%B8%AA%E8%AF%B7%E6%B1%82%E3%80%82%20%E6%9C%AA%E7%BB%8F%E9%AA%8C%E8%AF%81%E7%9A%84%E8%AF%B7%E6%B1%82%E4%B8%8E%E5%8E%9F%E5%A7%8B%20IP%20%E5%9C%B0%E5%9D%80%E7%9B%B8%E5%85%B3%E8%81%94%EF%BC%8C%E4%B8%8E%E5%8F%91%E5%87%BA%E8%AF%B7%E6%B1%82%E7%9A%84%E4%B8%AA%E4%BA%BA%E6%97%A0%E5%85%B3%E3%80%82)
