### ISSUE TITLE
任务栏图标出错

### ISSUE THREAD

**Issue by 30000lightyears** [MaaAssistantArknights/MaaX#101]
![image](https://user-images.githubusercontent.com/66123770/233431542-81751e89-56e4-4c68-bb93-9f0a2c08b8cc.png)
牛牛不见了（bushi

**Comment by ChingCdesu** [comment]
[v2.0.0-beta.4](https://github.com/MaaAssistantArknights/MaaX/releases/tag/v2.0.0-beta.4)中已修复
