### ISSUE TITLE
多设备切换bug

### ISSUE THREAD

**Issue by 1004452714** [MaaAssistantArknights/MaaX#102]
三个模拟器分别备注A1,A2,A3
![image](https://user-images.githubusercontent.com/28773469/233431124-73a2cbcc-2a3c-4ae7-9cc5-a71c1cda4d34.png)
在这个界面点击A1，变成下边的样子，看起来正常。
![image](https://user-images.githubusercontent.com/28773469/233431307-9ccf92d3-9bd6-4a6d-824d-e6e20cc2d950.png)
再点A2，变成下边的样子，看起来好像有些不正常了，A1没了
![image](https://user-images.githubusercontent.com/28773469/233431616-70665dd4-a861-47bc-9ff1-e51b7c986921.png)
再点当前设备里的A2,发现备注名是A1，adb的端口号也是A1的
![image](https://user-images.githubusercontent.com/28773469/233431758-8d8b832e-b801-492b-b182-ba8f3ef8f8ea.png)

![image](https://user-images.githubusercontent.com/28773469/233431981-093f002d-bb42-4c33-ba12-cdd41d48f475.png)
![image](https://user-images.githubusercontent.com/28773469/233432017-7199eecc-582e-4049-9046-d20a0c5e079b.png)

**Comment by fireflame-opx** [comment]
我也出现这个bug，并且bug出现后几秒钟之内MaaX发生闪退

**Comment by ChingCdesu** [comment]
fixed in v2.0.0-beta.6
