### ISSUE TITLE
详细信息模式下，任务卡片的控件可用属性设置错误

### ISSUE THREAD

**Issue by zlm324** [MaaAssistantArknights/MaaX#104]
在详细信息模式下，启动任务组，被启用的任务卡片上面，控件没有被禁用；
停止任务组后，上述控件反而被禁用了；
将卡片右上角的启用按钮切换一次后，卡片上的控件又恢复可用。

**Comment by ChingCdesu** [comment]
[v2.0.0-beta.4](https://github.com/MaaAssistantArknights/MaaX/releases/tag/v2.0.0-beta.4)中已修复
