### ISSUE TITLE
换班中途显示无法读取基建文件、停止后无法修改配置、肉鸽显示异常、关闭maax后无法再次连接问题

### ISSUE THREAD

**Issue by cenfusheng** [MaaAssistantArknights/MaaX#105]
日志：
[Maa App-20230421.log](https://github.com/MaaAssistantArknights/MaaX/files/11292102/Maa.App-20230421.log)

换班中途显示无法读取基建文件
![image](https://user-images.githubusercontent.com/52312717/233538121-ab23fd5d-2f56-4954-8d86-c4ad261ba902.png)

停止后无法修改配置
![image](https://user-images.githubusercontent.com/52312717/233538190-b212bac2-e657-4a12-bb37-e910f2f665d9.png)

选择水月肉鸽后，肉鸽配置仍显示傀影肉鸽选项
![image](https://user-images.githubusercontent.com/52312717/233538457-8013dec1-75cc-4f7c-9e5b-77dc9f05d65f.png)
![image](https://user-images.githubusercontent.com/52312717/233538487-1b04638f-afa3-446e-bcef-3201d1dd149a.png)

关闭maax后无法再次连接
![image](https://user-images.githubusercontent.com/52312717/233538674-07cff275-88ca-4783-b25c-fbb14349d1c3.png)
![image](https://user-images.githubusercontent.com/52312717/233538617-c66bc5e5-9150-496e-950f-abc6ffc67ab6.png)

**Comment by bakashigure** [comment]
肉鸽会在新版本中修复
