### ISSUE TITLE
自动肉鸽选取水月主题后，会跳转至傀影肉鸽，无法开始任务

### ISSUE THREAD

**Issue by CommandoBoris** [MaaAssistantArknights/MaaX#106]
maax-通用-肉鸽主题-水月
![Clip_20230421_122440](https://user-images.githubusercontent.com/107940834/233540524-e501263e-e592-4695-9dce-96f6e677b809.png)

无限刷肉鸽界面，无以人为本分队，心胜于物分队，物尽其用分队。
![image](https://user-images.githubusercontent.com/107940834/233540669-1fe13382-891b-42a3-8cb9-61791063a59b.png)

执行该任务，maa会转至傀影肉鸽界面，且在难度选择处卡住，然后单击开始，无限触发-请选择难度。
![Screenshot_2023 04 21_12 31 53 623](https://user-images.githubusercontent.com/107940834/233541393-f5a988e5-ab8a-4f23-b28d-aa300221fd1f.png)

maacore版本：v4.15.0-beta.1
maa app版本：v2.0.0-beta 2

**Comment by bakashigure** [comment]
会在新版本中修复
