### ISSUE TITLE
无法删除任务

### ISSUE THREAD

**Issue by gypsyzz** [MaaAssistantArknights/MaaX#109]
![image](https://user-images.githubusercontent.com/40400110/233552050-436c1bc1-a687-4af0-9c27-d302a761783a.png)
只能添加新任务组的，但是不能删除
（可能是另外的issue)
希望添加后可以重命名任务组，而不是#1，2，3，4，5

**Comment by ChingCdesu** [comment]
[v2.0.0-beta.4](https://github.com/MaaAssistantArknights/MaaX/releases/tag/v2.0.0-beta.4)支持了任务组重命名和删除
