### ISSUE TITLE
启动时报错: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by KiligLin** [MaaAssistantArknights/MaaX#113]
我看之前的issues修复好了这事，现在又出现了，beta3又出现这事了
![image](https://user-images.githubusercontent.com/97935169/233623036-f71cf3e5-c616-4b6c-a11b-7a5471d7c6fc.png)

**Comment by KiligLin** [comment]
win10，之前beta2一直有点奇奇怪怪的，删了重新下了个beta3，结果出现这个情况了

**Comment by builder0w0** [comment]
我也有相同情况，第一次打开没有反应，但是任务管理器有后台进程，再打开就会报这个错

**Comment by ChingCdesu** [comment]
这个和之前的问题不一样，溯源出来是有一个依赖打包的时候没有构建，试试能不能修掉这个问题

**Comment by ChingCdesu** [comment]
在[v2.0.0-beta.4](https://github.com/MaaAssistantArknights/MaaX/releases/tag/v2.0.0-beta.4)中修复
