### ISSUE TITLE
安装核心组件卡死

### ISSUE THREAD

**Issue by KiligLin** [MaaAssistantArknights/MaaX#119]
### 问题描述

点击安装立马卡死，
![image](https://user-images.githubusercontent.com/97935169/233757158-b147d4d8-c9d7-43c8-814e-a9527561c5e3.png)

### 日志文件

[Maa App-20230422.log](https://github.com/MaaAssistantArknights/MaaX/files/11300068/Maa.App-20230422.log)

### 截图

![image](https://user-images.githubusercontent.com/97935169/233757199-5c107744-646d-4376-87e0-812a79e33d9e.png)

**Comment by ChingCdesu** [comment]
这个是已知问题，和Maa核心组件有关。
未来版本中会以侧载的方式加载核心组件，避免MaaX失去响应，这应该需要一点时间（
