### ISSUE TITLE
界面显示和保存配置有异常

### ISSUE THREAD

**Issue by interfacew** [MaaAssistantArknights/MaaX#120]
### 1. 在重复多次添加相同ip地址时正在连接的上方提示会永久存在
![image](https://user-images.githubusercontent.com/131514634/233770161-65a0668b-d9cc-46ad-9d04-2327961c37bb.png)
### 2.在重启maa后添加设备在config里变为unknown，点击连接没用，有报错弹窗
重启前：
![image](https://user-images.githubusercontent.com/131514634/233770201-3aa6c669-7243-4b8f-ab34-14c0978741d4.png)
重启后：
![image](https://user-images.githubusercontent.com/131514634/233770227-31d35c71-dded-4b23-8be7-c0a1688c03cb.png)

**Comment by interfacew** [comment]
记错换行了直接发出来了我的问题
界面问题：
![image](https://user-images.githubusercontent.com/131514634/233770329-424cec44-1291-41a5-89e9-bb83076f5ca0.png)
### 4.肉鸽选人设置未保存
![image](https://user-images.githubusercontent.com/131514634/233770389-3d106e21-0d6b-4dac-9212-3b06fde93775.png)
重启后：
![image](https://user-images.githubusercontent.com/131514634/233770423-e0f4b858-5de9-4447-84c4-a95814309592.png)
### 5.多设备在切换时显示错误
如果有两个模拟器
![image](https://user-images.githubusercontent.com/131514634/233770490-6c10df6f-a8ed-45ec-a469-bd1be251d20d.png)
在这个界面下点击其他设备中的另一个设备
![image](https://user-images.githubusercontent.com/131514634/233770505-af402d4c-0279-46c9-b67c-b2d12376abdf.png)
![image](https://user-images.githubusercontent.com/131514634/233770524-93c0b022-d7c6-4b63-bfd0-74b961b3d021.png)
任务组和设备名会发生变化，而设备详情不会，同时两个设备显示的名字会变成后续点击的，这时候再次点击其他设备中的设备也不会发生变化
### 6.设备备注编辑不方便使用
目前在编辑设备备注名的时候如果删除了最后一个字符则备注会被修改成对应设备的uuid，在修改的时候较为不便，同时在gui中修改的备注长度最多只有11个字符

**Comment by interfacew** [comment]
[Maa App-20230422.log](https://github.com/MaaAssistantArknights/MaaX/files/11300592/Maa.App-20230422.log)

**Comment by ChingCdesu** [comment]
all issues fixed
