### ISSUE TITLE
自动肉鸽选取水月主题后，会跳转至傀影肉鸽，无法开始任务

### ISSUE THREAD

**Issue by longshensanjie** [MaaAssistantArknights/MaaX#123]
### 问题描述

跟前面一哥们提的bug相同，只不过这次是最新版本

执行该任务，maa会转至傀影肉鸽界面，且在难度选择处卡住，然后单击开始，无限触发-请选择难度。

maacore版本：v4.15.0-beta.2
maa app版本：v2.0.0-beta 4

**Comment by bakashigure** [comment]
会在新版本中修复
