### ISSUE TITLE
已连接设备保存问题

### ISSUE THREAD

**Issue by DBLLX** [MaaAssistantArknights/MaaX#124]
### 问题描述

1. 每次重新打开MaaX时，曾经连接过的模拟器地址并未保存；
2. 无法为模拟器地址添加备注。首先，无法将默认备注清空；其次，无法输入中文内容。

### 截图

![image](https://user-images.githubusercontent.com/93808534/233818932-ce4190c7-4c9e-4106-b39f-c5ad00bc8e27.png)

**Comment by ChingCdesu** [comment]
fixed in v2.0.0-beta.6
