### ISSUE TITLE
蓝叠无法连接

### ISSUE THREAD

**Issue by SteveWang92** [MaaAssistantArknights/MaaX#125]
### 问题描述

无法连接蓝叠，刷新时提示找不到可用设备，填ip连接时失败。旧版可以正常运行

### 日志文件

[Maa App-20230423.log](https://github.com/MaaAssistantArknights/MaaX/files/11303087/Maa.App-20230423.log)

### 截图

![7WZ3TF{H6`2}89HD}4ET58I](https://user-images.githubusercontent.com/26997414/233826081-86dd128c-748a-445b-9e16-3d259cf57c41.png)

### 还有别的吗？

版本	Windows 10 企业版
版本号	21H2
安装日期	‎2022/‎1/‎10
操作系统内部版本	19044.2846
体验	Windows Feature Experience Pack 120.2212.4190.0

蓝叠 5.11.1.1002 n32

**Comment by bakashigure** [comment]
日志里最后一行的`stdout`和`stderr`的输出是啥

**Comment by matser39** [comment]
![8G10W%9OZF%M24VW5}6@VCG](https://user-images.githubusercontent.com/94966993/233838378-4ac7bd8e-dade-4ac6-9a69-012e2c9f9f3e.png)蓝叠模拟器的adb地址在这里，至少我的尾数是5575

**Comment by SteveWang92** [comment]
已解决，path里没有powershell所以无法调用也没有输出，添加`C:\Windows\System32\WindowsPowerShell\v1.0`之后可以正常运行
