### ISSUE TITLE
无法启动模拟器

### ISSUE THREAD

**Issue by UniMars** [MaaAssistantArknights/MaaX#127]
### 问题描述

我使用的是蓝叠国际版模拟器，端口号每次启动时都会变化，没有固定的端口号
之前老版maa可以做到启动模拟器，并自动识别最新的端口号
现在maax手动输入已经启动的模拟器地址（127.0.0.1:xxx）可以识别并连接
但是模拟器关闭后就无法识别并启动模拟器了（报错device.noAvailableDevice）
老版maa有选项记录模拟器的adb地址，maaX似乎只能记录端口号，不知道是不是跟这个有关系

**Comment by bakashigure** [comment]
左边那个按钮是个搜索功能，用于搜索当前正在运行的模拟器，它应该是能搜到你正在运行的蓝叠国际版并且记录住启动指令的

**Comment by UniMars** [comment]
> 左边那个按钮是个搜索功能，用于搜索当前正在运行的模拟器，它应该是能搜到你正在运行的蓝叠国际版并且记录住启动指令的

在蓝叠已经启动的情况下，点刷新还是会报错 “刷新设备列表失败, 请重试”， 只有手动输入端口号并点击刷新下面的连接才能连上。
如果是在蓝叠没有启动的情况下，maax不能自动启动模拟器，必须要手动启动蓝叠。

**Comment by bakashigure** [comment]
麻烦传一份日志上来, 日志在 `%appdata%\maa-x\logs` 内, 
**日志内可能含有你的隐私信息**

**Comment by UniMars** [comment]
[Maa App-20230423.log](https://github.com/MaaAssistantArknights/MaaX/files/11304156/Maa.App-20230423.log)

**Comment by bakashigure** [comment]
请问您是如何启动蓝叠模拟器的，是通过桌面上的快捷方式启动还是其他的方式

**Comment by UniMars** [comment]
> 请问您是如何启动蓝叠模拟器的，是通过桌面上的快捷方式启动还是其他的方式

就是maa里有一个选项记录了蓝叠的hd-player.exe地址，我只要打开maa，蓝叠就会自动启动了

**Comment by bakashigure** [comment]
试一下手动启动蓝叠，就是通过蓝叠的快捷方式启动，然后再试试使用maa-x的搜索功能

**Comment by UniMars** [comment]
> 试一下手动启动蓝叠，就是通过蓝叠的快捷方式启动，然后再试试使用maa-x的搜索功能

[屏幕录制 2023-04-24 001037.zip](https://github.com/MaaAssistantArknights/MaaX/files/11304198/2023-04-24.001037.zip)

**Comment by bakashigure** [comment]
好奇怪。。。 麻烦再右击一下蓝叠的快捷方式，点 **属性** , 然后再点击一下 **快捷方式** , 然后把第三个字段 **目标** 拖到最后，然后截个图，麻烦了！
![image](https://user-images.githubusercontent.com/33803916/233851655-97e4891b-9f6c-4ab9-bbec-ab158391dad2.png)

**Comment by UniMars** [comment]
![image](https://user-images.githubusercontent.com/65664032/233851969-ea7356b8-a98c-4f6c-8ff6-3b309dd98be1.png)

**Comment by interfacew** [comment]
这个好像跟 #130 是一个问题
都是在获取启动指令的时候powershell返回了一个null然后寄了
我之前也遇到过这个问题
当时我问题的原因是使用管理员身份打开模拟器后运行maax
但这时的maa可能因为权限问题无法获取到执行路径
![image](https://user-images.githubusercontent.com/131514634/234072593-37dbb9a4-acb8-410a-a6b9-972985f42ac8.png)
提高到管理员运行就可以正常获取了
![image](https://user-images.githubusercontent.com/131514634/234072740-831be092-8b92-4c28-9961-0e3172a894e3.png)
只是一种可能性，但我认为可以试试
