### ISSUE TITLE
自动启动模拟器闪退

### ISSUE THREAD

**Issue by bakashigure** [MaaAssistantArknights/MaaX#128]
### 问题描述

自动启动模拟器闪退

**Comment by UniMars** [comment]
我也遇到了这个问题，是在这个问题 #127 解决后发现的。
具体来说就是用管理员模式启动maa-x，连接上蓝叠后，在蓝叠已经启动的情况下启动任务`启动模拟器`会发生maa-x闪退

**Comment by Nothing1031** [comment]
4.28 23之后更新了核心组件一直闪退，系统win11，模拟器MuMu，不管有没有开模拟器都会闪退
