### ISSUE TITLE
鼠标移动时界面模糊

### ISSUE THREAD

**Issue by Bohejiabing** [MaaAssistantArknights/MaaX#134]
### 问题描述

刚启动时界面清晰（p1），鼠标移动后变模糊（p2），鼠标悬停时悬停处清晰（p3）
之前在其他软件中也出现过这个问题，通过“禁用GPU加速”选项解决了

### 截图

![image](https://user-images.githubusercontent.com/90741643/234197497-9f26c721-b0bf-4f02-8cd6-07f90acca57a.png)
![image](https://user-images.githubusercontent.com/90741643/234197680-e9f6f5a5-384b-47fe-a6ff-440f721ab057.png)
![image](https://user-images.githubusercontent.com/90741643/234197976-a403e519-b6f7-438b-861d-d1e82091cac3.png)

**Comment by ChingCdesu** [comment]
可能是你显卡驱动有问题导致的
