### ISSUE TITLE
任务界面功能性优化

### ISSUE THREAD

**Issue by YoYueze** [MaaAssistantArknights/MaaX#137]
### 说说你遇到的问题？

任务界面目前只能全部简略显示或者详细显示，希望可以单独点开一个选项进行单独设置
<img width="764" alt="屏幕截图 2023-04-25 204743" src="https://user-images.githubusercontent.com/80182838/234282630-efa4f985-8525-45f4-bb69-434ef8457610.png">

**Comment by neko-para** [comment]
![image](https://user-images.githubusercontent.com/26452623/234622440-41904cea-a2e3-4bc1-aa0f-afd859dac6b8.png)
