### ISSUE TITLE
核心安装失败

### ISSUE THREAD

**Issue by IranksAdral** [MaaAssistantArknights/MaaX#142]
### 问题描述

核心安装失败，操作停止在启动模拟器后……

### 日志文件

[Maa App-20230427.log](https://github.com/MaaAssistantArknights/MaaX/files/11338708/Maa.App-20230427.log)

### 截图

![X3)(M`I1A2_2{F)KGJY{8U7](https://user-images.githubusercontent.com/87361258/234737824-17b8d215-a5a8-435a-8cbc-0f2cf427e5e0.png)
![}}5I7M8F{@%4`L NV 75Q$F](https://user-images.githubusercontent.com/87361258/234737842-2930eddb-f860-4868-bdcd-f4e425d51f8a.png)

### 还有别的吗？

win10

**Comment by ChingCdesu** [comment]
排查一下网络问题

**Comment by Lemon-miaow** [comment]
It is possible that a 400 bad request error occurred while using the proxy, causing the installation to fail.
![image](https://user-images.githubusercontent.com/61692393/235306466-577ae482-3418-421b-ac6e-140bb5377745.png)
