### ISSUE TITLE
界面按钮逻辑优化？

### ISSUE THREAD

**Issue by Eziodeng** [MaaAssistantArknights/MaaX#143]
### 说说你遇到的问题？

![image](https://user-images.githubusercontent.com/49717931/234748322-e8939a84-6acd-4d00-99c0-0ba7231f8727.png)
rt, 切换任务这边对着每一栏点了半天，发现得按那个小的按钮切换简单/详细

### 有什么好的想法？

点击具体的任务栏切换到相应的详细设置界面？
（或者是否能够点击某一栏弹出相应这一栏的详细设置的一个小窗口？

**Comment by neko-para** [comment]
参考#137 局部展开功能已经实现
