### ISSUE TITLE
任务删掉后点击当前设备又会重新出现

### ISSUE THREAD

**Issue by Feng-HelloWorld** [MaaAssistantArknights/MaaX#146]
### 问题描述

1. 选择设备，在任务界面点减号删除几个任务；
2. 点击当前设备；
3. 删掉的任务会自动冒出来，无限肉鸽还自动打开了。

### 截图

https://user-images.githubusercontent.com/52819906/234892343-5468fab4-47bc-4a60-bfd0-89f2c73a2705.mp4

### 还有别的吗？

雷电9
WIndows11
Maa版本beta4和beta5都有出现

**Comment by neko-para** [comment]
同#139 已经修了
