### ISSUE TITLE
新版UI的全选和反选功能

### ISSUE THREAD

**Issue by chesha1** [MaaAssistantArknights/MaaX#152]
### 在提问之前...

- [X] 我填写了简短且清晰明确的标题，以便开发者在翻阅 issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等
- [X] 我基本确定这是一个新功能/建议，而不是遇到了 bug（不确定的话请附上日志）

### 说说你遇到的问题？

新版UI里，没有旧版有的全选和反选功能
这个感觉还是挺实用的呢，比如要打肉鸽，可以一键选择，不然还要点七个键

**Comment by chesha1** [comment]
> 其实为什么不试试新开一个任务组呢 🤔

请问哪里能开一个新的任务组，➕按钮好像只能添加单个种类的任务啊

**Comment by chesha1** [comment]
你好，@neko-para
请问哪里能开一个新的任务组，➕按钮好像只能添加单个种类的任务啊

**Comment by bakashigure** [comment]
> 你好，@neko-para 请问哪里能开一个新的任务组，➕按钮好像只能添加单个种类的任务啊

红框下拉
![image](https://user-images.githubusercontent.com/33803916/235211635-94c890db-c596-4f54-94c9-b89a3bf58bb0.png)

**Comment by chesha1** [comment]
> > 你好，@neko-para 请问哪里能开一个新的任务组，➕按钮好像只能添加单个种类的任务啊
> 
> 红框下拉 ![image](https://user-images.githubusercontent.com/33803916/235211635-94c890db-c596-4f54-94c9-b89a3bf58bb0.png)

macos版本的UI好像有点不一样，上图是Windows端的界面吗？

<img width="1280" alt="截屏2023-04-29 上午9 38 31" src="https://user-images.githubusercontent.com/49867392/235277788-f7d2a765-91b5-498d-a17a-966023378ad5.png">

**Comment by chesha1** [comment]
好像有点不太对，我又去Windows电脑上下载了一下maax，界面和上图不一样，如果maax是用electron做的跨平台做的话，界面应该是一样的？所以上图并不是maax而是maa的一个版本？
我之前从Windows迁移到macos看到ui变了，所以下意识感觉这就是新版ui，所以其实并不是对吗？
那么macos版本的maa是否就没有全选和反选的功能，还是说上图这个maa属于一个旧版本，更新到新版本就好了？

**Comment by neko-para** [comment]
> 好像有点不太对，我又去Windows电脑上下载了一下maax，界面和上图不一样，如果maax是用electron做的跨平台做的话，界面应该是一样的？所以上图并不是maax而是maa的一个版本？ 我之前从Windows迁移到macos看到ui变了，所以下意识感觉这就是新版ui，所以其实并不是对吗？ 那么macos版本的maa是否就没有全选和反选的功能，还是说上图这个maa属于一个旧版本，更新到新版本就好了？

大概是因为还在dev上没进Release(

**Comment by neko-para** [comment]
诶, 你mac上用的什么啊, 是maax吗
