### ISSUE TITLE
macOS文件损坏无法打开

### ISSUE THREAD

**Issue by lethefrost** [MaaAssistantArknights/MaaX#154]
### 问题描述

系统窗口报错`“maa-x.app”已损坏，无法打开。 你应该将它移到废纸篓。`

### 还有别的吗？

macOS Ventura 13.3.1，arm64（M2 Max）
maa-x 2.0.0-beta.5

**Comment by ChingCdesu** [comment]
没应用程序签名，需要在 设置->隐私与安全性 里面信任MaaX

**Comment by ChingCdesu** [comment]
那更新版本试试呢

**Comment by ChingCdesu** [comment]
> 那更新版本试试呢

哦 macOS，现在还不能自动安装core
