### ISSUE TITLE
有图片挂掉的提示

### ISSUE THREAD

**Issue by WSMTBG** [MaaAssistantArknights/MaaX#155]
### 问题描述

![图片](https://user-images.githubusercontent.com/32087250/235163167-63751de3-54e0-4da2-972c-b787b718a4be.png)
如图，然后挂机功能是做什么的？

**Comment by neko-para** [comment]
这里计划是放定时更新的模拟器截图, 目前还没做, 所以这里没有数据

**Comment by WSMTBG** [comment]
> 这里计划是放定时更新的模拟器截图, 目前还没做, 所以这里没有数据

请问挂机功能是什么呢

**Comment by ChingCdesu** [comment]
挂机功能后面会删除，这个是之前替代经典版maa的定时任务的，但是效果不是很好，也有许多问题
