### ISSUE TITLE
MaaX安装Core后无限闪退

### ISSUE THREAD

**Issue by Meet-Li** [MaaAssistantArknights/MaaX#156]
### 问题描述

MaaX安装完Core后自行关闭，之后只要打开就闪退，管理员运行同样闪退

### 日志文件

[Maa App-20230429.log](https://github.com/MaaAssistantArknights/MaaX/files/11355377/Maa.App-20230429.log)

### 还有别的吗？

MUMU模拟器，操作系统Win10 64位。

**Comment by bakashigure** [comment]
试一下清空`%appdata%\maa-x`这整个路径?

**Comment by GalaxyEmpire** [comment]
应该是core的问题，我刚试过用旧版MAA直接覆盖掉%appdata%\maa-x\core里面的文件就可以正常打开了
