### ISSUE TITLE
启动任务后主程序闪退

### ISSUE THREAD

**Issue by xingyu1272** [MaaAssistantArknights/MaaX#157]
### 问题描述

启动任务数秒后主程序闪退

### 日志文件

[Maa App-20230429.log](https://github.com/MaaAssistantArknights/MaaX/files/11358003/Maa.App-20230429.log)

### 还有别的吗？

模拟器：蓝叠国际版
MAA Core：v4.15.2-alpha.1.d123.g823d32b5
顺便 好像没有找到定时执行的设置

**Comment by xingyu1272** [comment]
尝试将v4.15.1的旧版本maa覆盖core文件夹里的15.2 运行后仍闪退

**Comment by ChingCdesu** [comment]
试试新版本有没有这个问题
