### ISSUE TITLE
蓝叠模拟器连接问题

### ISSUE THREAD

**Issue by Rs-Pluma** [MaaAssistantArknights/MaaX#159]
### 问题描述

![image](https://user-images.githubusercontent.com/75989333/235826905-01f2f23b-2ee5-4d99-8aae-8b0c2118cb4f.png)
蓝叠模拟器 Hyper-V 版本自动连接不上，只能手动连接。

### 日志文件

![image](https://user-images.githubusercontent.com/75989333/235827636-552554f2-b285-4c08-a412-d86a5614b2a0.png)
蓝叠模拟器 Hyper-V 版本安装路径是BlueStacks_nxt_cn，但我看winAdapter.ts并没有相关的代码，是还没有适配吗？

**Comment by bakashigure** [comment]
修了 [0f173d3](https://github.com/MaaAssistantArknights/maa-core-server/commit/0f173d3541b51534c1b8699e68dad21b51bb7149)
