### ISSUE TITLE
模拟器多开对某一模拟器自定义名称问题

### ISSUE THREAD

**Issue by ZhiJuan0724** [MaaAssistantArknights/MaaX#160]
### 问题描述

夜神模拟器多开对某一模拟器自定义名称时会让其他模拟器同步更改

如下图，是两个地址并不相同的设备

先对模拟器二命名为"夜神模拟器-Maa"
再对模拟器一重命名为"夜神模拟器-Alas"
导致模拟器二显示的名称改变为"夜神模拟器-Alas"
但是在模拟器二的详细信息里仍保留着上次的信息即"夜神模拟器-Maa"

### 日志文件

[Maa App-20230509.log](https://github.com/MaaAssistantArknights/MaaX/files/11428152/Maa.App-20230509.log)

### 截图

模拟器1(localhost:62001)：
![KZ9{)0T@@54BT} `LH3C8J8](https://user-images.githubusercontent.com/36944634/237015767-2e38699a-ddce-4575-9fa5-36869ffff323.png)

模拟器2(localhost:62025)：
![MTZ5Z(_90Q48)LW9QL5A}Y](https://user-images.githubusercontent.com/36944634/237015867-e949e48b-4d0b-4e49-85a0-bb5a45c8990a.png)

**Comment by ZhiJuan0724** [comment]
详细信息的窗口就是上一次，命名的名字
对设备一重命名为夜神模拟器-Alas
导致设备二显示的名称改变
但是在详细信息里仍保留着上次的信息

**Comment by ChingCdesu** [comment]
fixed in v2.0.0-beta.6
