### ISSUE TITLE
安装核心组件时提示 “MAA核心组件安装失败”

### ISSUE THREAD

**Issue by RIFTaReLINK** [MaaAssistantArknights/MaaX#164]
### 问题描述

版本：maa-x-linux-x64-2.0.0-beta.7
系统：Manjaro (Gnome) 
内核：6.3.2-zen1-1-zen (linux63)

### 日志文件

2023-05-24 15:21:12.393 INFO  [main resources/app/packages/main/index.ts:55  _f] module WindowManager-v1.0.0 loaded. 
2023-05-24 15:21:12.411 INFO  [main resources/app/packages/main/index.ts:55  _f] module StorageManager-v1.0.0 loaded. 
2023-05-24 15:21:12.413 INFO  [main resources/app/packages/main/index.ts:55  _f] module CoreLoader-v1.0.0 loaded. 
2023-05-24 15:21:12.415 INFO  [main resources/app/packages/main/index.ts:55  _f] module DeviceDetector-v1.0.0 loaded. 
2023-05-24 15:21:12.416 INFO  [main resources/app/packages/main/index.ts:55  _f] module DownloadManager-v1.0.0 loaded. 
2023-05-24 15:21:12.417 INFO  [main resources/app/packages/main/index.ts:55  _f] module ComponentManager-v1.0.0 loaded. 
2023-05-24 15:21:12.970 INFO  [main resources/app/packages/main/coreLoader/index.ts:527  gn.Upgrade] Start upgrade core 
2023-05-24 15:21:12.972 INFO  [main resources/app/packages/main/coreLoader/index.ts:543  gn.Upgrade] [CoreLoader] Start upgrade core, current version: CUR_NOT_FOUND, upgrade version: v4.18.1, upgrade file: MAA-v4.18.1-linux-x86_64.tar.gz 
2023-05-24 15:21:13.067 ERROR [main resources/app/packages/main/coreLoader/index.ts:314  gn.load] ENOENT: no such file or directory, open '/home/relie/.config/maa-x/core/libopencv_world4.so.407' 
2023-05-24 15:21:13.070 ERROR [main resources/app/packages/main/coreLoader/index.ts:128  gn.dispose] close core error 
2023-05-24 15:21:13.075 DEBUG [renderer resources/app/packages/main/utils/logger.ts:56 undefined.<anonymous>] finish loading store 
2023-05-24 15:21:23.059 DEBUG [main resources/app/packages/main/componentManager/utils/update.ts:95  Os.checkUpdate] 
[
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470835',
    id: 109470835,
    node_id: 'RA_kwDOFutQ4s4GhmRz',
    name: 'MAA-v4.18.1-linux-aarch64.tar.gz',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/gzip',
    state: 'uploaded',
    size: 134380863,
    download_count: 423,
    created_at: '2023-05-23T17:10:00Z',
    updated_at: '2023-05-23T17:10:05Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAA-v4.18.1-linux-aarch64.tar.gz'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470836',
    id: 109470836,
    node_id: 'RA_kwDOFutQ4s4GhmR0',
    name: 'MAA-v4.18.1-linux-x86_64.tar.gz',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/gzip',
    state: 'uploaded',
    size: 137286664,
    download_count: 20,
    created_at: '2023-05-23T17:10:00Z',
    updated_at: '2023-05-23T17:10:06Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAA-v4.18.1-linux-x86_64.tar.gz'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470838',
    id: 109470838,
    node_id: 'RA_kwDOFutQ4s4GhmR2',
    name: 'MAA-v4.18.1-macos-universal.dmg',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/octet-stream',
    state: 'uploaded',
    size: 167199678,
    download_count: 55,
    created_at: '2023-05-23T17:10:01Z',
    updated_at: '2023-05-23T17:10:07Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAA-v4.18.1-macos-universal.dmg'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470839',
    id: 109470839,
    node_id: 'RA_kwDOFutQ4s4GhmR3',
    name: 'MAA-v4.18.1-win-arm64.zip',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/zip',
    state: 'uploaded',
    size: 132913696,
    download_count: 148,
    created_at: '2023-05-23T17:10:01Z',
    updated_at: '2023-05-23T17:10:05Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAA-v4.18.1-win-arm64.zip'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470840',
    id: 109470840,
    node_id: 'RA_kwDOFutQ4s4GhmR4',
    name: 'MAA-v4.18.1-win-x64.zip',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/zip',
    state: 'uploaded',
    size: 134276761,
    download_count: 2142,
    created_at: '2023-05-23T17:10:01Z',
    updated_at: '2023-05-23T17:10:07Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAA-v4.18.1-win-x64.zip'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470837',
    id: 109470837,
    node_id: 'RA_kwDOFutQ4s4GhmR1',
    name: 'MAAComponent-DebugSymbol-v4.18.1-macos-universal.zip',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/zip',
    state: 'uploaded',
    size: 4655154,
    download_count: 9,
    created_at: '2023-05-23T17:10:00Z',
    updated_at: '2023-05-23T17:10:01Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAAComponent-DebugSymbol-v4.18.1-macos-universal.zip'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470842',
    id: 109470842,
    node_id: 'RA_kwDOFutQ4s4GhmR6',
    name: 'MAAComponent-DebugSymbol-v4.18.1-win-arm64.zip',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/zip',
    state: 'uploaded',
    size: 11946287,
    download_count: 10,
    created_at: '2023-05-23T17:10:01Z',
    updated_at: '2023-05-23T17:10:02Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAAComponent-DebugSymbol-v4.18.1-win-arm64.zip'
  },
  {
    url: 'https://gh.cirno.xyz/api.github.com/repos/MaaAssistantArknights/MaaAssistantArknights/releases/assets/109470841',
    id: 109470841,
    node_id: 'RA_kwDOFutQ4s4GhmR5',
    name: 'MAAComponent-DebugSymbol-v4.18.1-win-x64.zip',
    label: '',
    uploader: {
      login: 'github-actions[bot]',
      id: 41898282,
      node_id: 'MDM6Qm90NDE4OTgyODI=',
      avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
      gravatar_id: '',
      url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D',
      html_url: 'https://gh.cirno.xyz/github.com/apps/github-actions',
      followers_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/followers',
      following_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
      gists_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
      starred_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
      subscriptions_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/subscriptions',
      organizations_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/orgs',
      repos_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/repos',
      events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
      received_events_url: 'https://gh.cirno.xyz/api.github.com/users/github-actions%5Bbot%5D/received_events',
      type: 'Bot',
      site_admin: false
    },
    content_type: 'application/zip',
    state: 'uploaded',
    size: 11916089,
    download_count: 31,
    created_at: '2023-05-23T17:10:01Z',
    updated_at: '2023-05-23T17:10:02Z',
    browser_download_url: 'https://gh.cirno.xyz/github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.18.1/MAAComponent-DebugSymbol-v4.18.1-win-x64.zip'
  }
]
2023-05-24 15:21:23.066 INFO  [main resources/app/packages/main/componentManager/utils/update.ts:106  Os.checkUpdate] [Component Installer | Maa Core] Found full asset: v4.18.1 
2023-05-24 15:21:23.067 INFO  [main resources/app/packages/main/downloadManager/index.ts:116  ji.download] Start downloading, url: https://s3.maa-org.net:25240/maa-release/MaaAssistantArknights/MaaAssistantArknights/releases/download/MAA-v4.18.1-linux-x86_64.tar.gz

**Comment by ChingCdesu** [comment]
ci做了相应的变更，这个问题在dev分支已经被修复了，但还没发版
