### ISSUE TITLE
linux 5.19内核 无法开始任务

### ISSUE THREAD

**Issue by Fuynkio** [MaaAssistantArknights/MaaX#167]
### 问题描述

版本是 2.0.0-beta8 (在这个时间点2.0.0-beta9刚出 我还没有试)
就按一下那个 开始 按钮 就会在终端报错

另外 显卡选混合模式会卡住一下 然后缓回来 （在混合模式和独显模式下都不能开始任务，只是有卡顿）

另另外 我似乎没有找到 最小化,关闭 的按钮

### 日志文件

我是在终端里用./maa-x打开的 就复制了终端显示的 
[byhand.log](https://github.com/MaaAssistantArknights/MaaX/files/11560893/byhand.log)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaX/assets/50935992/bc0d1ad2-1d7c-4bd6-bf8a-717f719aa979)

### 还有别的吗？

Linux Mint    
内核：5.19.0-42-generic 
530独显驱动

**Comment by ChingCdesu** [comment]
duplicate #163

**Comment by bakashigure** [comment]
试一下新版(beta10)看看问题是否解决

**Comment by Fuynkio** [comment]
解决了
