### ISSUE TITLE
增加log记录，特别是GUI.LOG

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#174]
### 说说你遇到的问题？

无法查看log来debug

### 有什么好的想法？

增加log记录，特别是GUI.LOG

**Comment by bakashigure** [comment]
`UI LOG` 在设置里可以快捷打开

**Comment by ChingCdesu** [comment]
你确定你说的是maa-x

**Comment by pein0saga** [comment]
> 你确定你说的是maa-x

没搜到log文件

**Comment by pein0saga** [comment]
> `UI LOG` 在设置里可以快捷打开

谢谢，我当时好像不知道为什么没搜到.log，可能换了储存方式

**Comment by pein0saga** [comment]
> 你确定你说的是maa-x

对不起，我错了 ゜(´□｀｡)°゜哭

**Comment by pein0saga** [comment]
> `UI LOG` 在设置里可以快捷打开

是我太天真单纯，没有经历充分的社会的拷打和洗礼，没有用老奸巨滑武装自己

发现了在C:\Users\Administrator\AppData\Roaming\maa-x\logs里面
