### ISSUE TITLE
任务卡片VIEW状态无法记忆，重启会把card-view退回到list view （连接了两个设备）

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#175]
### 问题描述

任务卡片VIEW状态无法记忆，重启会把卡片状态退回列表状态

连接了两个设备

_No response_

**Comment by neko-para** [comment]
是指那个展开与否的状态吗

**Comment by pein0saga** [comment]
> 是指那个展开与否的状态吗

从上往下的list-view 和 2xN阵列的card-view的切换

**Comment by ChingCdesu** [comment]
这是期望的，详细模式下切换设备会由于控件太多在低配设备下的卡顿，所以默认是列表

**Comment by pein0saga** [comment]
> 这是期望的，详细模式下切换设备会由于控件太多在低配设备下的卡顿，所以默认是列表

了解了，这是为了考虑性能做的默认的功能优化
