### ISSUE TITLE
删除任务会删除“delete”按钮下面的任务

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#176]
### 问题描述

删除任务会删除“delete”按钮下面的任务

**Comment by ZhiJuan0724** [comment]
甚至于有时候不是删除而是复制
有点没懂怎么回事
但是稳定复现

**Comment by ZhiJuan0724** [comment]
https://github.com/MaaAssistantArknights/MaaX/assets/36944634/351293ec-5199-4fbb-b2d8-43e6cbba7252

**Comment by bakashigure** [comment]
> 甚至于有时候不是删除而是复制 有点没懂怎么回事 但是稳定复现

我这里没能复现成功，麻烦提供一个复现方式

**Comment by pein0saga** [comment]
> 甚至于有时候不是删除而是复制 有点没懂怎么回事 但是稳定复现

对的，发现不但删偏了，而且删一个复制另一个

**Comment by pein0saga** [comment]
> > 甚至于有时候不是删除而是复制 有点没懂怎么回事 但是稳定复现
> 
> 我这里没能复现成功，麻烦提供一个复现方式

试试双开模拟器能不能复现，不知道和#177的成因有没有相通类似的地方

**Comment by ZhiJuan0724** [comment]
我是有两个模拟器 但只开了一个

**Comment by ZhiJuan0724** [comment]
https://github.com/MaaAssistantArknights/MaaX/assets/36944634/54ce2fb7-820c-4aa6-866b-54380ff0e7c4
