### ISSUE TITLE
ADB位置自定义？避免只能强制新安装独立的

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#178]
### 说说你遇到的问题？

电脑里带adb的程序有很多，尽可能削减。
我个人习惯性MAA和ALAS的adb共用，防止同时运行的时候adb相互冲突（好像有这种说法）

**Comment by ChingCdesu** [comment]
不保证adb可用，很多模拟器自带了adb，不同版本的adb也会互相kill。

**Comment by pein0saga** [comment]
> 不同版本的adb也会互相kill。

我用的ALAS项目的adb（蓝叠的ADB名字就很奇怪），有时候我要开2个不同模拟器，加MAA,加ALAS，就是为了尽可能减少同时运行的不同版本的adb的数量。自定义就提供了这种灵活性
