### ISSUE TITLE
MAA核心组件残留可能引起的问题（比想象的复杂，难以复现）

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#179]
### 说说你遇到的问题？

前两天还能够秒装（后来删了），现在重下但两个镜像都装不了，都是0%。一直都是全局TUN模式，联网没问题。

**Comment by pein0saga** [comment]
<img width="718" alt="Snipaste_2023-05-28_21-04-05" src="https://github.com/MaaAssistantArknights/MaaX/assets/2074641/a7540cac-dc41-4fb0-95b9-fc613b51595d">

**Comment by pein0saga** [comment]
至少报个NETWORK ERROR 或者permission denied之类的

**Comment by ChingCdesu** [comment]
都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了

**Comment by pein0saga** [comment]
> 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了

我知道原因了，是因为之前MAA CORE没有卸载的问题

**Comment by bakashigure** [comment]
> > 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了
> 
> 1 我知道原因了，是因为之前MAA CORE没有卸载的问题
> 
> 2 全局TUN proxy，我没说过只上网易（~百du退散~）啊？而且两个镜像国内国外都用了，假设是只上网易的网络环境问题，那就是国内镜像有问题。
> 
> 3 MAA CORE 需要单独的install/uninstall、Update机制，根本没检测出来已安装

1. 出于#150, `maa-x`目前使用的是重启更新的方式, 下载与更新是互不影响的
2. 大概率是网络问题
3. `core`目前是有完整的热更功能, 同样出于 #150, 暂时使用重启更新

**Comment by pein0saga** [comment]
> > > 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了
> > 
> > 
> > 1 我知道原因了，是因为之前MAA CORE没有卸载的问题
> > 2 全局TUN proxy，我没说过只上网易（~百du退散~）啊？而且两个镜像国内国外都用了，假设是只上网易的网络环境问题，那就是国内镜像有问题。
> > 3 MAA CORE 需要单独的install/uninstall、Update机制，根本没检测出来已安装
> 
> 1. 出于[MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), `maa-x`目前使用的是重启更新的方式, 下载与更新是互不影响的
> 2. 大概率是网络问题
> 3. `core`目前是有完整的热更功能, 同样出于 [MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), 暂时使用重启更新

我删除了core文件夹就立马能更新了，这会是网络问题？太固执了吧？我在另一个issue里面已经上传了log和报错信息，看完log再下结论比较好

**Comment by pein0saga** [comment]
> > > 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了
> > 
> > 
> > 1 我知道原因了，是因为之前MAA CORE没有卸载的问题
> > 2 全局TUN proxy，我没说过只上网易（~百du退散~）啊？而且两个镜像国内国外都用了，假设是只上网易的网络环境问题，那就是国内镜像有问题。
> > 3 MAA CORE 需要单独的install/uninstall、Update机制，根本没检测出来已安装
> 
> 1. 出于[MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), `maa-x`目前使用的是重启更新的方式, 下载与更新是互不影响的
> 2. 大概率是网络问题
> 3. `core`目前是有完整的热更功能, 同样出于 [MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), 暂时使用重启更新

我表达能力有限，可能让你误解过。我说的update的不是狭义的程序联网的“自动更新或者热更新”，而是广义上的文件替换，“update local files”，手动覆盖文件（不管前后版本的差别）。

你的技术实现对我来说是黑盒，我可能的不准确的表述和用词可能会让你产生误解或者理解上的偏差。
1. beta 10 beta9 似乎就是同一个内容的程序，应该就是版本号有点差别，但主体内容相同，core应该也相同。

2. 我一共下载过两次，第一次beta 10 或者 beta9 都有可能（release顺序颠倒问题），第二次是beta 10

3. 第一次下载估计27日左右。删掉了主题程序文件，留下了core在C盘。第二次下载28日，重新解压，运行，出现MAAX无法识别C盘的admin目录下的core（可能和管理员权限有关、也可能无关，win的权限太复杂 ），提示缺失core，要我安装。然后一直stuck在0%， 看日志，29日9：00的时候，旧的core是加载成功的（其实是同版本core），true，但是我依然卡在下载页面stuck 0%。

4. 29日10：00的时候，猫猫问我删掉core目录能不能更新，我马上删了core。成功热更新（准确来说是热安装，因为同版本的core已经被我手动删除了，删除admin目录需要特定高权限）。如果你还要坚持说就是大概率网络问题，大概率删了core+-几秒之内突然国内国外同时通网了，我无话可说。

**Comment by pein0saga** [comment]
你可以自己检查这个评论的timestamp是不是10:0x

https://github.com/MaaAssistantArknights/MaaX/issues/150#issuecomment-1566391205

**Comment by ChingCdesu** [comment]
还有一种可能是你的ip地址请求了过多数量的GitHub api，达到了rate limit

**Comment by pein0saga** [comment]
我暂时不就结了这个了，有时候时间点重合也许会让我判断错误,如果有人复现了再开吧

**Comment by pein0saga** [comment]
> > > > > 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了
> > > > 
> > > > 
> > > > 1 我知道原因了，是因为之前MAA CORE没有卸载的问题
> > > > 2 全局TUN proxy，我没说过只上网易（~百du退散~）啊？而且两个镜像国内国外都用了，假设是只上网易的网络环境问题，那就是国内镜像有问题。
> > > > 3 MAA CORE 需要单独的install/uninstall、Update机制，根本没检测出来已安装
> > > 
> > > 
> > > 
> > > 1. 出于[MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), `maa-x`目前使用的是重启更新的方式, 下载与更新是互不影响的
> > > 2. 大概率是网络问题
> > > 3. `core`目前是有完整的热更功能, 同样出于 [MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), 暂时使用重启更新
> > 
> > 
> > 我删除了core文件夹就立马能更新了，这会是网络问题？太固执了吧，在极其有限的信息下，根据偏见去下概率结论毫无意义。我在另一个issue里面已经上传了log和报错信息，看完log再下结论比较好
> 
> 你的日志我看过，所以我会说` 下载与更新是互不影响的`，既然你不了解技术实现细节，所以你不应该坚持这不是一个网络问题
> 
> 至于详细情况，我仍然认为这是两个问题
> 
> 1. 下载卡在0%
> 2. core加载失败
> 
> 对于第一点，我要重申的是`下载`, `更新` 和 `加载core` 三者是完全独立的模块，下载就只是下载安装包到`download`文件夹，不会影响现有的`core`, 因为现在更新必须重启；更新是在启动后比`加载core`更优先执行的东西；`加载core`会尝试加载本地的core, 出错情况下才会运行用户重新下载安装
> 
> 对于第二点, `win error 126` 意味着 `core加载失败`，详细原因就是`DLL缺失`，`core`大概在4.16前后修改过一次依赖库，如果你的旧`core`是这个版本左右的，那么可能会出现这个报错； 另一种情况是, 在更新的时候, `maa-x`被错误关闭了，导致解压流程进行到一半就被结束了，文件损坏同样有可能出现`win error 126`

我建议下载中的时候，“下载源”变成不可切换的灰色状态，否则切换也是无效的，或者会损坏热更新的压缩包

**Comment by pein0saga** [comment]
> 导致解压流程进行到一半就被结束了，文件损坏同样有可能出现win error 126

0 用的都是最新版

1.被错误关闭损坏以后最好弹个错误框（比如再MD5验证安装包完整性），否则一直卡在下载上，别人都以为一直在下载（但实际上提前解压了）

2. “下载安装中。。。”：安装进度条和下载进度条应该分成两种，经常看不出来到底是在安装还是下载。

3. 我第一次都是秒下载秒安装，后来就要好几分钟，挺迷的

**Comment by pein0saga** [comment]
今天故意删了主程序故意残留了下，直接识别core了。核心组件残留可能是必要条件，但不是充分条件。

**Comment by pein0saga** [comment]
应该是更复杂的情况
