### ISSUE TITLE
 Dynamic Linking Error: Win32 error 126 

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#180]
应该是热更新zip安装包损坏导致（提前关闭）
和普通游戏的OTA更新不一样，没有校验

### 问题描述

```
2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:314  mn.load] Dynamic Linking Error: Win32 error 126 
2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:128  mn.dispose] close core error 
2023-05-29 08:59:41.461 DEBUG [renderer resources\app\packages\main\utils\logger.ts:56 undefined.<anonymous>] finish loading store 
2023-05-29 08:59:47.335 INFO  [main resources\app\packages\main\componentManager\utils\update.ts:106  Os.checkUpdate] [Component Installer | Maa Core] Found full asset: v4.19.0-beta.2 
2023-05-29 08:59:47.342 INFO  [main resources\app\packages\main\downloadManager\index.ts:116  ji.download] Start downloading, url: https://s3.maa-org.net:25240/maa-release/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.19.0-beta.2/MAA-v4.19.0-beta.2-win-x64.zip 
2023-05-29 09:03:17.055 INFO  [main resources\app\packages\main\utils\extract.ts:95  cf] extracting file: C:\Users\Administrator\AppData\Roaming\maa-x\download\MAA-v4.19.0-beta.2-win-x64.zip -> C:\Users\Administrator\AppData\Roaming\maa-x\core 
2023-05-29 09:03:21.014 INFO  [main resources\app\packages\main\coreLoader\index.ts:310  mn.load] core loaded: version v4.19.0-beta.2 
2023-05-29 09:03:21.068 INFO  [renderer resources\app\packages\main\utils\logger.ts:62 undefined.<anonymous>] [LoadResource] type: CN, path: C:\Users\Administrator\AppData\Roaming\maa-x\core, status: true 
```

### 日志文件

[Maa App-20230529.log](https://github.com/MaaAssistantArknights/MaaX/files/11587522/Maa.App-20230529.log)

**Comment by bakashigure** [comment]
> ### 问题描述
> 我这边应该是同版本的core冲突。非同版本不知道是否不同。
> 
> #179 检测不到，无法覆盖升级（被误诊关闭）
> 
> #150 @neko-para 猫猫问题联动
> 
> > ### 问题描述
> > MAA Core 4.13后的版本无法被dispose, 导致无法进行更新
> 
> ```
> 2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:314  mn.load] Dynamic Linking Error: Win32 error 126 
> 2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:128  mn.dispose] close core error 
> 2023-05-29 08:59:41.461 DEBUG [renderer resources\app\packages\main\utils\logger.ts:56 undefined.<anonymous>] finish loading store 
> 2023-05-29 08:59:47.335 INFO  [main resources\app\packages\main\componentManager\utils\update.ts:106  Os.checkUpdate] [Component Installer | Maa Core] Found full asset: v4.19.0-beta.2 
> 2023-05-29 08:59:47.342 INFO  [main resources\app\packages\main\downloadManager\index.ts:116  ji.download] Start downloading, url: https://s3.maa-org.net:25240/maa-release/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.19.0-beta.2/MAA-v4.19.0-beta.2-win-x64.zip 
> 2023-05-29 09:03:17.055 INFO  [main resources\app\packages\main\utils\extract.ts:95  cf] extracting file: C:\Users\Administrator\AppData\Roaming\maa-x\download\MAA-v4.19.0-beta.2-win-x64.zip -> C:\Users\Administrator\AppData\Roaming\maa-x\core 
> 2023-05-29 09:03:21.014 INFO  [main resources\app\packages\main\coreLoader\index.ts:310  mn.load] core loaded: version v4.19.0-beta.2 
> 2023-05-29 09:03:21.068 INFO  [renderer resources\app\packages\main\utils\logger.ts:62 undefined.<anonymous>] [LoadResource] type: CN, path: C:\Users\Administrator\AppData\Roaming\maa-x\core, status: true 
> ```
> 
> ### 日志文件
> [Maa App-20230529.log](https://github.com/MaaAssistantArknights/MaaX/files/11587522/Maa.App-20230529.log)
> 
> ### 手动解决方法
> > 所以你手动删了core目录之后可以正常更新了吗
> 
> _Originally posted by @neko-para in [#150 (comment)](https://github.com/MaaAssistantArknights/MaaX/issues/150#issuecomment-1566366778)_
> 
> 解决方法就是手动删掉系统盘用户文件夹的core目录，但萌新可能不知道位置

看你提供的这段日志，这不是更新成功了吗

**Comment by pein0saga** [comment]
> > ### 问题描述
> > 我这边应该是同版本的core冲突。非同版本不知道是否不同。
> > #179 检测不到，无法覆盖升级（被误诊关闭）
> > #150 @neko-para 猫猫问题联动
> > > ### 问题描述
> > > MAA Core 4.13后的版本无法被dispose, 导致无法进行更新
> > 
> > 
> > ```
> > 2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:314  mn.load] Dynamic Linking Error: Win32 error 126 
> > 2023-05-29 08:59:41.459 ERROR [main resources\app\packages\main\coreLoader\index.ts:128  mn.dispose] close core error 
> > 2023-05-29 08:59:41.461 DEBUG [renderer resources\app\packages\main\utils\logger.ts:56 undefined.<anonymous>] finish loading store 
> > 2023-05-29 08:59:47.335 INFO  [main resources\app\packages\main\componentManager\utils\update.ts:106  Os.checkUpdate] [Component Installer | Maa Core] Found full asset: v4.19.0-beta.2 
> > 2023-05-29 08:59:47.342 INFO  [main resources\app\packages\main\downloadManager\index.ts:116  ji.download] Start downloading, url: https://s3.maa-org.net:25240/maa-release/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.19.0-beta.2/MAA-v4.19.0-beta.2-win-x64.zip 
> > 2023-05-29 09:03:17.055 INFO  [main resources\app\packages\main\utils\extract.ts:95  cf] extracting file: C:\Users\Administrator\AppData\Roaming\maa-x\download\MAA-v4.19.0-beta.2-win-x64.zip -> C:\Users\Administrator\AppData\Roaming\maa-x\core 
> > 2023-05-29 09:03:21.014 INFO  [main resources\app\packages\main\coreLoader\index.ts:310  mn.load] core loaded: version v4.19.0-beta.2 
> > 2023-05-29 09:03:21.068 INFO  [renderer resources\app\packages\main\utils\logger.ts:62 undefined.<anonymous>] [LoadResource] type: CN, path: C:\Users\Administrator\AppData\Roaming\maa-x\core, status: true 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 日志文件
> > [Maa App-20230529.log](https://github.com/MaaAssistantArknights/MaaX/files/11587522/Maa.App-20230529.log)
> > ### 手动解决方法
> > > 所以你手动删了core目录之后可以正常更新了吗
> > 
> > 
> > _Originally posted by @neko-para in [#150 (comment)](https://github.com/MaaAssistantArknights/MaaX/issues/150#issuecomment-1566366778)_
> > 解决方法就是手动删掉系统盘用户文件夹的core目录，但萌新可能不知道位置
> 
> 看你提供的这段日志，这不是更新成功了吗

你不知道前应后果。这是load成功（load的core文件夹的内容，上次卸载遗留的）。但实际上界面是卡在“正在更新core”0%的画面上，也就是说它判断我需要安装core（虽然已经core load成功，但load的core不是现在下载的的，而是上个版本遗留的，上个版本其实也是BETA 10，所以应该是同版本）

**Comment by pein0saga** [comment]
> > > > 都是0%那就是你网络问题，你能上百度不代表你能上谷歌，我这里只是举个例子，你连不到github和我们s3服务器那就是你自己网络炸了
> > > 
> > > 
> > > 1 我知道原因了，是因为之前MAA CORE没有卸载的问题
> > > 2 全局TUN proxy，我没说过只上网易（~百du退散~）啊？而且两个镜像国内国外都用了，假设是只上网易的网络环境问题，那就是国内镜像有问题。
> > > 3 MAA CORE 需要单独的install/uninstall、Update机制，根本没检测出来已安装
> > 
> > 
> > 
> > 1. 出于[MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), `maa-x`目前使用的是重启更新的方式, 下载与更新是互不影响的
> > 2. 大概率是网络问题
> > 3. `core`目前是有完整的热更功能, 同样出于 [MAA Core无法正常卸载 #150](https://github.com/MaaAssistantArknights/MaaX/issues/150), 暂时使用重启更新
> 
> 我删除了core文件夹就立马能更新了，这会是网络问题？太固执了吧，在极其有限的信息下，根据偏见去下概率结论毫无意义。我在另一个issue里面已经上传了log和报错信息，看完log再下结论比较好

你的日志我看过，所以我会说` 下载与更新是互不影响的`，既然你不了解技术实现细节，所以你不应该坚持这不是一个网络问题

至于详细情况，我仍然认为这是两个问题
1. 下载卡在0%
2. core加载失败

对于第一点，我要重申的是`下载`, `更新` 和 `加载core` 三者是完全独立的模块，下载就只是下载安装包到`download`文件夹，不会影响现有的`core`, 因为现在更新必须重启；更新是在启动后比`加载core`更优先执行的东西；`加载core`会尝试加载本地的core, 出错情况下才会运行用户重新下载安装

对于第二点, `win error 126` 意味着 `core加载失败`，详细原因就是`DLL缺失`，`core`大概在4.16前后修改过一次依赖库，如果你的旧`core`是这个版本左右的，那么可能会出现这个报错； 另一种情况是, 在更新的时候, `maa-x`被错误关闭了，导致解压流程进行到一半就被结束了，文件损坏同样有可能出现`win error 126`

_Originally posted by @bakashigure in https://github.com/MaaAssistantArknights/MaaX/issues/179#issuecomment-1566891164_

**Comment by pein0saga** [comment]
应该是热更新zip安装包损坏导致（提前关闭）
和普通游戏的OTA更新不一样，似乎没有校验
