### ISSUE TITLE
组件下载、安装过程中下载源的切换选项按钮应该被灰掉锁起来

### ISSUE THREAD

**Issue by pein0saga** [MaaAssistantArknights/MaaX#182]
### 说说你遇到的问题？

<img width="731" alt="Snipaste_2023-05-30_12-29-06" src="https://github.com/MaaAssistantArknights/MaaX/assets/2074641/5a8b4d48-b1f1-4097-823d-c05f51399fd5">

组件下载、安装“过程”中，不应该让下载源的切换按钮有效。

（实际带来的危害要么是数据包损坏，要么带来“已经成功切换了”的误解）

真要强制切换的话，加个停止按钮再切换，并且后台删除已下载的不完整数据（如果有的话）。

### 有什么好的想法？

组件安装过程中下载源的切换选项按钮应该被灰掉锁起来。真要强制切换的话，加个停止按钮再切换，并且后台删除已下载的不完整数据（如果有的话）。

**Comment by ChingCdesu** [comment]
你随便切换，只有按了开始安装的按钮这玩意才有用

**Comment by pein0saga** [comment]
> 你随便切换，只有按了开始安装的按钮这玩意才有用

你的意思就是：“开始安装”按过以后，任何的切换行为都是无效的，不会造成任何可能的干扰。

**Comment by ChingCdesu** [comment]
不会
