### ISSUE TITLE
回调消息 ConnectionInfo 和 ConnectionError 拆开

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/MaaX#50]
想把 `AsstMsg`::`ConnectionInfo` 中的错误消息拆出来，先问下 ui 好改么（

即 `ConnectionInfo` 一律是通知信息； `ConnectionError` 一律是报错，代表 core 会停止运行

**Comment by MistEO** [comment]
时雨——

@bakashigure

**Comment by bakashigure** [comment]
你拆啊 随便拆.jpg

**Comment by ChingCdesu** [comment]
回调部分被重构

**Comment by bakashigure** [comment]
草 我不是开了 https://github.com/MaaAssistantArknights/MaaAsstElectronUI/issues/69
