### ISSUE TITLE
mumu模拟器连不上

### ISSUE THREAD

**Issue by HMZyueshen** [MaaAssistantArknights/MaaX#56]
![P_EGMA0A {U(S}P0EPC$(@R](https://user-images.githubusercontent.com/106477016/187336302-b50b7422-688d-40b9-aa53-359a9a03978e.png)
而且连接失败后上面的模拟器连接中会一直存在

**Comment by ChingCdesu** [comment]
时雨 救救 @bakashigure

**Comment by bakashigure** [comment]
@HMZyueshen 麻烦端一份 log 上来, 我这里能跑.jpg  log 文件在`%appdata%\meo-assistant-arknights\logs`
![image](https://user-images.githubusercontent.com/33803916/187449715-a39c22d2-cd38-4169-87a9-bd1ee8228972.png)

**Comment by HMZyueshen** [comment]
[Maa App.log](https://github.com/MaaAssistantArknights/MaaAsstElectronUI/files/9456396/Maa.App.log)

**Comment by ChingCdesu** [comment]
重新启动后还得刷新一下
初始化的时候会清掉所有模拟器的连接地址，这个修一下 @bakashigure

**Comment by HMZyueshen** [comment]
但还是连不上

**Comment by ChingCdesu** [comment]
麻烦检查一下以下项目：
1. 设置中`Android 设备连接组件`是否正确安装
2. 模拟器的调试模式是否开启，并确认端口号为7555
3. 还不行我也没法了，只有等 @bakashigure 来解决问题o(╯□╰)o

**Comment by bakashigure** [comment]
看看`%appdata%\meo-assistant-arknights\core\platform-tools`下面有没有`adb`的可执行程序 Orz
目前这份log并不能看出是为啥没连上

**Comment by HMZyueshen** [comment]
![image](https://user-images.githubusercontent.com/106477016/187857087-fbba7221-769b-4dec-93d4-20070fc650bf.png)

**Comment by ChingCdesu** [comment]
通知不关闭的问题倒是修了，我们需要一些时间重新考虑怎么打log，现在log的部分很多重要的信息都没打印。但是这些信息可能会包括某些个人隐私，所以这个问题需要讨论一段时间。

**Comment by bakashigure** [comment]
修了一些连接上的问题，要不试试a14？

**Comment by bakashigure** [comment]
已支持mumu12
