### ISSUE TITLE
连接到雷电模拟器时出错，并且输出的信息中中文出现乱码

### ISSUE THREAD

**Issue by Randark-JMT** [MaaAssistantArknights/MaaX#81]
![图片](https://user-images.githubusercontent.com/56223739/206454714-f0fd7edd-cecf-4714-9a6f-4ec99047ec69.png)

但是手动通过adb连接的时候没有问题
![图片](https://user-images.githubusercontent.com/56223739/206455125-2ef4c324-e38f-4952-9076-c7ae1bd96a8b.png)

**Comment by Randark-JMT** [comment]
可能和中文乱码有关？

**Comment by Randark-JMT** [comment]
中文信息来自于雷电模拟器的输出，改变模拟器多开的名称就变成：
![图片](https://user-images.githubusercontent.com/56223739/206455647-079b1ce6-75df-4e39-a9d3-e8ca1fc095a6.png)
同时提示：“Maa Core不兼容”

**Comment by ChingCdesu** [comment]
- 中文乱码与终端的编码有关，Windows终端默认编码是936 GBK，ui的日志默认编码是65001 utf-8，ui日志会先由windows认为的GBK解码，然后转换成终端编码显示。
- 问题`MAA Core不兼容`与模拟器无关，应该和最近MAA修改了接口有关

**Comment by bakashigure** [comment]
![image](https://user-images.githubusercontent.com/33803916/206644635-776cfea2-e6d7-4be4-b234-79e3a9a206de.png)
连上了，但并没有完全连上，尝试重启模拟器
