### ISSUE TITLE
MaaX多设备检索出错

### ISSUE THREAD

**Issue by PianCat** [MaaAssistantArknights/MaaX#99]
![Snipaste_2023-04-20_23-40-24](https://user-images.githubusercontent.com/50688679/233417577-01654678-81f8-49f4-aa8b-a7ecf22e638a.png)
雷电模拟器的ADB我已经替换成了Android Platform Tools原版的ADB，并且每个连接点都手动连接过一次，无效

**Comment by ChingCdesu** [comment]
可以的话，将位于`C:\Users\你的用户名\AppData\Roaming\maa-x\logs`内的相关log文件上传，以便于开发们寻找问题
**注：log文件内可能包含了你电脑的所有进程信息，这属于敏感信息，你可以拒绝上传log**

**Comment by ChingCdesu** [comment]
这个问题应该最近的迭代中修了
